version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: dev_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dev_database"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared_network

  rr-store:
    build: .
    container_name: rr-store
    ports:
      - "8080:8080"
    env_file:
      - secrets.env
    depends_on:
      postgres-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  postgres_data:
