apiVersion: apps/v1
kind: Deployment
metadata:
  name: rr-store
  labels:
    app: rr-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rr-store
  template:
    metadata:
      labels:
        app: rr-store
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      dnsPolicy: ClusterFirst
      containers:
        - name: rr-store
          image: tylerpritchard/rr-store:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: rr-store-secret
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
