apiVersion: apps/v1
kind: Deployment
metadata:
  name: rr-store
  labels:
    app: rr-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rr-store
  template:
    metadata:
      labels:
        app: rr-store
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: rr-store
        image: rr-store:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: rr-store-secret  # Correctly referenced secret
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
